--require("claude-code").setup({
--  -- Terminal window settings
--  window = {
--    split_ratio = 0.3,      -- Percentage of screen for the terminal window (height for horizontal, width for vertical splits)
--    position = "botright",  -- Position of the window: "botright", "topleft", "vertical", "float", etc.
--    enter_insert = true,    -- Whether to enter insert mode when opening Claude Code
--    hide_numbers = true,    -- Hide line numbers in the terminal window
--    hide_signcolumn = true, -- Hide the sign column in the terminal window
--    
--    -- Floating window configuration (only applies when position = "float")
--    float = {
--      width = "80%",        -- Width: number of columns or percentage string
--      height = "80%",       -- Height: number of rows or percentage string
--      row = "center",       -- Row position: number, "center", or percentage string
--      col = "center",       -- Column position: number, "center", or percentage string
--      relative = "editor",  -- Relative to: "editor" or "cursor"
--      border = "rounded",   -- Border style: "none", "single", "double", "rounded", "solid", "shadow"
--    },
--  },
--  -- File refresh settings
--  refresh = {
--    enable = true,           -- Enable file change detection
--    updatetime = 100,        -- updatetime when Claude Code is active (milliseconds)
--    timer_interval = 1000,   -- How often to check for file changes (milliseconds)
--    show_notifications = true, -- Show notification when files are reloaded
--  },
--  -- Git project settings
--  git = {
--    use_git_root = true,     -- Set CWD to git root when opening Claude Code (if in git project)
--  },
--  -- Shell-specific settings
--  shell = {
--    separator = '&&',        -- Command separator used in shell commands
--    pushd_cmd = 'pushd',     -- Command to push directory onto stack (e.g., 'pushd' for bash/zsh, 'enter' for nushell)
--    popd_cmd = 'popd',       -- Command to pop directory from stack (e.g., 'popd' for bash/zsh, 'exit' for nushell)
--  },
--  -- Command settings
--  command = "claude",        -- Command used to launch Claude Code
--  -- Command variants
--  command_variants = {
--    -- Conversation management
--    continue = "--continue", -- Resume the most recent conversation
--    resume = "--resume",     -- Display an interactive conversation picker
--
--    -- Output options
--    verbose = "--verbose",   -- Enable verbose logging with full turn-by-turn output
--  },
--  -- Keymaps
--  keymaps = {
--    toggle = {
--      normal = "<C-,>",       -- Normal mode keymap for toggling Claude Code, false to disable
--      terminal = "<C-,>",     -- Terminal mode keymap for toggling Claude Code, false to disable
--      variants = {
--        continue = "<leader>cC", -- Normal mode keymap for Claude Code with continue flag
--        verbose = "<leader>cV",  -- Normal mode keymap for Claude Code with verbose flag
--      },
--    },
--    window_navigation = true, -- Enable window navigation keymaps (<C-h/j/k/l>)
--    scrolling = true,         -- Enable scrolling keymaps (<C-f/b>) for page up/down
--  }
--})

--require('codecompanion').setup({
--    interactions = {
--        chat = {
--            adapter = "anthropic",
--        },
--        inline = {
--            adapter = "anthropic",
--        },
--        cmd = {
--            adapter = "anthropic",
--        },
--    },
--    adapters = {
--        anthropic = require("codecompanion.adapters").extend("anthropic", {
--          env = {
--            api_key = function()
--              return vim.fn.system("pass show claude/api-key"):gsub("\n", "")
--            end
--            }
--        }),
--    },
--})

--require('minuet').setup {
--    provider = 'openai_fim_compatible',
--    n_completions = 1, -- recommend for local model for resource saving
--    -- I recommend beginning with a small context window size and incrementally
--    -- expanding it, depending on your local computing power. A context window
--    -- of 512, serves as an good starting point to estimate your computing
--    -- power. Once you have a reliable estimate of your local computing power,
--    -- you should adjust the context window to a larger value.
--    context_window = 512,
--    provider_options = {
--        openai_fim_compatible = {
--            -- For Windows users, TERM may not be present in environment variables.
--            -- Consider using APPDATA instead.
--            api_key = function()
--                  return vim.fn.system("pass show claude/api-key"):gsub("\n", "")
--                end,
--            name = 'Llama.cpp',
--            end_point = 'http://localhost:8012/v1/completions',
--            -- The model is set by the llama-cpp server and cannot be altered
--            -- post-launch.
--            model = 'PLACEHOLDER',
--            optional = {
--                max_tokens = 56,
--                top_p = 0.9,
--            },
--            -- Llama.cpp does not support the `suffix` option in FIM completion.
--            -- Therefore, we must disable it and manually populate the special
--            -- tokens required for FIM completion.
--            template = {
--                prompt = function(context_before_cursor, context_after_cursor, _)
--                    return '<|fim_prefix|>'
--                        .. context_before_cursor
--                        .. '<|fim_suffix|>'
--                        .. context_after_cursor
--                        .. '<|fim_middle|>'
--                end,
--                suffix = false,
--            },
--        },
--    },
--    lsp = {
--        enabled_ft = { 'toml', 'lua', 'cpp', 'rust' },
--        -- Enables automatic completion triggering using `vim.lsp.completion.enable`
--        enabled_auto_trigger_ft = { 'cpp', 'lua', 'rust', 'markdown' },
--    },
--    virtualtext = {
--        auto_trigger_ft = {'md', 'cpp', 'lua', 'rust'},
--        
--        keymap = {
--            -- accept whole completion
--            accept = '<C-g>',
--            -- accept one line
--            accept_line = '<leader-C-g>',
--            -- accept n lines (prompts for number)
--            -- e.g. "A-z 2 CR" will accept 2 lines
--            --accept_n_lines = '<A-z>',
--            -- Cycle to prev completion item, or manually invoke completion
--            --prev = '<A-[>',
--            -- Cycle to next completion item, or manually invoke completion
--            --next = '<A-]>',
--            --dismiss = '<A-e>',
--        },
--    },
--}
